/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.0.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "puzzles"

include("lib")

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            val kotlinVersion = "2.2"

            version("mockito.kotlin", "5.4.0")
            version("detekt", "1.23.7")
            version("junit5", "5.13.4")

            plugin("kotlin.jvm", "org.jetbrains.kotlin.jvm").version(kotlinVersion)
//            plugin("kotlin.jpa", "org.jetbrains.kotlin.plugin.jpa").version(kotlinVersion)
            plugin("detekt", "io.gitlab.arturbosch.detekt").versionRef("detekt")
        }
    }
}
